export { default as Instrumentos } from './Instrumentos'
export { default as FechaNacimiento } from './FechaNacimiento'
export { default as Genero } from './Genero'
export { default as GenerosMusicales } from './GenerosMusicales'
export { default as Pais } from './Pais'
export { default as Ciudad } from './Ciudad'
export { default as Experiencia } from './Experiencia'
export { default as RedesSociales } from './RedesSociales'
export { default as Telefono } from './Telefono'

